### ISSUE TITLE
As a site visitor, I want to see a timer counting down from 108 minutes, including the seconds

### ISSUE THREAD

**Issue by Brandeau** [Brandeau/lost-countdown-timer#2]
**Tasks**

- [x] Design the structure of the countdown terminal
- [x] Create the HTML that implements the design
- [x] Develop the functionality of the countdown

**Acceptance criteria**

- [x] When I load the page, I should see a timer begin to countdown from 108 minutes and 00 seconds 

![Image](https://github.com/Brandeau/lost-countdown-timer/assets/40775995/66ac248f-baec-41ab-94b6-b98754336407)

**Out-of-Scope**

- [x] Developing the functionality after the timer reaches zero
