### ISSUE TITLE
As a user, I want to be able to enter the password (4 8 15 16 23 42) so that the countdown resets

### ISSUE THREAD

**Issue by Brandeau** [Brandeau/lost-countdown-timer#3]
**Tasks**

- [x] Design the input area
- [x] Create the HTML for the input area design
- [x] Develop the functionality of the input area so that when the correct password is entered the timer resets to 108 minutes 00 seconds

**Acceptance criteria**

- [x] When I enter the correct password, the timer will reset
- [x] When I enter an incorrect password, the timer will not reset
- [x] When I press Enter, whether correct or incorrect, the terminal will move to the next line

![Image](https://github.com/Brandeau/lost-countdown-timer/assets/40775995/58136c81-884e-4c6a-b2a3-e832f14c10a9)

![Image](https://github.com/Brandeau/lost-countdown-timer/assets/40775995/0d3b3133-70cb-430c-97a4-cafb5b305654)

**Out-of-Scope**

- [x] Develop the functionality after the timer hits zero
