### ISSUE TITLE
As a user, I want to hear an alarm go off if I haven’t entered the password when the timer reaches 4 minutes so that I know time is running out

### ISSUE THREAD

**Issue by Brandeau** [Brandeau/lost-countdown-timer#4]
**Tasks**

- [x] Create the functionality of an alarm that goes off when the timer reaches 4 minutes

**Acceptance Criteria**

- [x] When the timer reaches 4, I should hear an alarm go off until the timer reaches zero or I input the correct password

**Out-Of-Scope**

- [x] Develop the functionality after the timer reaches zero
